### ISSUE TITLE
Scroll 관련 layout 수정

### ISSUE THREAD

**Issue by Ring-wdr** [u-ga-u-ga/front-end#24]
<img width="618" alt="image" src="https://github.com/u-ga-u-ga/front-end/assets/70439662/b7181b69-377d-40e7-98d8-a027325abed3"><br/>
정상적인 전역 스크롤 이벤트 감지를 위해 레이아웃 수정이 필요합니다.

**Comment by aliveornot** [comment]
![image](https://github.com/u-ga-u-ga/front-end/assets/60848153/e931368c-0ff9-4613-adb2-64915d0b13ab)

https://github.com/u-ga-u-ga/front-end/assets/60848153/9e4eaebd-f443-4bc0-b088-54c010fad64d

context provider로 content container(600px짜리)의 스크롤 상태를 내려주는 방식으로 해결하면 어떨까 하는데, 의견 주시면 감사하겠습니다. 괜찮으신 것 같으면 코드 정리해볼게요. 

브랜치는 푸시해 두었고, 해당 브랜치에서 /scrolltest로 접근하시면 확인해보실 수 있습니다.

**Comment by Ring-wdr** [comment]
전체 페이지가 리렌더링 방식은 오버헤드가 클 거 같아서 레이아웃을 수정하는 방향으로 추가로 찾아보겠습니다만,
이 방식으로 고려하신다면 기본 제공 훅으로 약간의 성능 최적화는 필요할 것 같습니다.

아래는 예시 코드입니다.
- useEffect 제거 후 callback ref 적용
  - dispatchAction 의존성 배열 추가로 의도치 않은 버그 발생 방지
- usetransition과 usedefferedvalue를 통한 상태 업데이트 지연 및 스크롤 값 우선순위 낮춤


```javascript

function RootComponent() {
  const [scrollPosition, setScrollPosition] = useState(0);
  const deferredScrollPostion = useDeferredValue(scrollPosition);
  const [, startTransition] = useTransition();
  const scrollCallbackRef = useCallback(
    (ref: HTMLDivElement | null) => {
      if (ref) {
        ref.scrollTop = 0;
        ref.addEventListener("scroll", handleScroll);
      }
      function handleScroll() {
        if (!ref) return;
        const position = ref.scrollTop;
        startTransition(() => setScrollPosition(position));
      }
    },
    [setScrollPosition, startTransition]
    // []
  );

  return (
    <>
      <div className="flex h-full justify-center gap-40">
        <div
          data-pc-layout
          className="hidden h-full w-80 gap-2 bg-white p-2 text-lg xl:flex"
        >
          가구고고
        </div>
        <div
          ref={scrollCallbackRef}
          className="h-full w-full max-w-[600px] overflow-scroll bg-white"
        >
          <ContentContainerScrollPositionContext.Provider
            value={deferredScrollPostion}
          >
            <Outlet />
          </ContentContainerScrollPositionContext.Provider>
        </div>
      </div>
      <ReactQueryDevtools buttonPosition="top-right" />
      <TanStackRouterDevtools position="bottom-right" />
    </>
  );
}

```

**Comment by aliveornot** [comment]
음 제가 정확히 이해한 것인지 모르겠는데, 

"전체 페이지가 리렌더링 방식은 오버헤드가 클 거 같아서 레이아웃을 수정하는 방향으로 추가로 찾아보겠습니다만,"

이 말씀이 혹시 스크롤 될 때마다 전체 페이지가 리렌더링 될 수 있어 문제라는 말씀이시라면, scrollPosition을 사용하는 header만 
`ContentContainerScrollPositionContext` 를 컨슘하면 될 것 같습니다.

**Comment by aliveornot** [comment]
아 이 페이지 자체가 리렌더링될거라 이말씀이셨군요 ㅋㅋ 
제 머리속에서는 당연히 분리할 생각이었습니다.  scrollContainer가 되는 div와 provider둘을 따로 빼서요.

**Comment by Ring-wdr** [comment]
비교 스크린샷과 같이 첨부해서 올려드립니다. (페이지 전체 외곽선 부분만 보시면 됩니다)
scrollPosition을 사용하는 header만 consume하더라도 스크롤 이벤트시에 provider로 감싼 부분이 하이라이팅이 되는 거 같아서요.
(이 부분은 __root를 감싸는 것이 아닌 메인만 감싸더라도 메인 전체는 하이라이팅이 됩니다.)
특정 element의 스크롤이벤트를 감지하는 것이 아닌 window객체의 스크롤이벤트를 감지하면, 아래 사진처럼 사용되는 부분만 하이라이팅이 됩니다.

이러한 이유는 window객체를 사용하는 것은 context를 이용할 필요가 없기 때문입니다. useSyncExternalStore혹은 커스텀 훅을 이용해서 listener에서만 스크롤 이벤트로 인한 값 변경을 감지할 수 있어서 그렇습니다.

![기존](https://github.com/u-ga-u-ga/front-end/assets/70439662/2c257fc0-1a8a-423b-bce1-87f73fb8b95f)
![제안](https://github.com/u-ga-u-ga/front-end/assets/70439662/44b05e7c-aa23-4806-8674-407a7dd36830)

**Comment by aliveornot** [comment]
결론적으로 하신 말씀이 맞는 것 같습니다.

말씀해주신 리렌더링 문제는 컨텍스트프로바이더 하위컴퍼넌트는 항상 리렌더링되기때문이라기 보다는,
현재 RootComponent()가 scrollPosition(state)를 가지고 있어 매번 리렌더링 되기 때문일텐데,

평소 jotai를 사용하다 보니 간단히 컨텍스트프로바이더 +  contentContainer를 분리할 수 있을 것이라고 생각했는데, 방금 해보니까 이게 useState, useContext 만 가지고는 구현이 되지 않는 것 같네요.

이런 경우라면 context를 내려주는 방법은 사용하면 안 될 것 같습니다. 

 ps.  contentContainer에 id를 부여하면 window사용하시는 것과 비슷하게 구현할 수 있을 것이라고 생각은 하는데, 이것도 별로 react-like하지 않은 것 같다는 생각이 드네요.

**Comment by Ring-wdr** [comment]
[feat/detectingScroll-2](https://github.com/u-ga-u-ga/front-end/tree/feat/detectingScroll-2)

저도 브랜치 새로 작성하여 레이아웃 수정 후 푸쉬하였습니다. detail 페이지에서 스크롤 y의 변화를 확인해보실 수 있습니다.
(당연히 피드백 이후 헤더에 붙인 scrollY 부분은 revert 입니다 ㅎㅎ)
dx적으로 불편한 부분이 있는 거 같아서 적극적인 피드백 부탁드립니다.
제가 생각하는 불편함은 <s>header가 fixed되지 않은 자연스러운 children은 상관이 없는데</s>
detail 페이지에서의 fixed된 헤더들에 대해서 max-width를 일일히 넣어줘야하는 부분입니다.

**Comment by aliveornot** [comment]
이거 생각보다는 훨씬 재밌는 문제였네요.

max-width관련해서, 불편함 보다는 뭔가 hierarchy가 깨지는 것 같다는 생각이 들어서 주신 코드 분기해서 container에 id를 부여하는 방향으로 처리해보았습니다. (id는 상수 처리해야할 것 같지만 그냥 지저분하게 작성해 두었습니다.)  max width문제는 사라지긴 하는데, 어떻게 보이시는지 궁금하네요. feat/detectingScroll-2-1입니다.

UI 개념적으로는 `#main-content-container` 가 fixed height를 가지게 되면서 좀 더 web보다는 app-like한 환경이 됩니다. 

+ 그런데 useSyncExternalStore를 사용하신 특별한 이유가 있나요? 그냥 useEffect/useState로 바인딩하지 않고요.

**Comment by Ring-wdr** [comment]
올려주신 코드 확인해보았습니다. 이론상으로는 모든 페이지들의 변경이 Outlet 내부에서 이루어지기 때문에 위계 질서가 확실해서 문제가 안 될 것 같기도 합니다. selector를 통해 event사용이 가능하다면, 해당 훅에 selector를 인자로 넘겨서 보다 위계질서가 보장된 상황에서 다른 컴포넌트에서도 확장성있게 사용이 가능할 것 같기도 합니다.

(+) useSyncExternalStore를 사용한 이유는 다음과 같습니다.
1. react 내부의 상태가 아닌 외부의 상태를 구독하기 위해서는 엄격한 방법이 필요하다고 생각했습니다.
[참고 링크](https://jser.dev/2023-08-02-usesyncexternalstore/)
2. useEffect가 보고 싶지 않아서.. (물론 useSyncExternalStore의 내부에는 state랑 effect가 있습니다.)

**Comment by aliveornot** [comment]
감사합니다. 링크로 주신 블로그 내용이 상당히 좋네요. useEffect자체가 outside react와의 syncing인 것으로 이해하고 있기는 한데 edgecase handling이 필요한 경우가 생길 수 있군요.

위계에 대한 이야기는 js코드보다는 UI에 대한 말씀이었긴 합니다. fixed가 되는 순간 최상단으로 가게 되는 것이라, 바깥쪽 wrapper가 변경된다든가, 모달의 backdrop과 충돌할 가능성이라든가 말이죠. 다만 현실적으로 저희 앱 수준에서 그게 문제가 될 상황이 있을거라고 생각하지는 않습니다. 사실 이리저리 생각해본 것으로 충분히 도움이 되었다고 생각해서, (어차피 만중님만 사용하게 될 가능성이 높기도 하니) 만중님  편하신 방법대로 결정하셔도 되지 않을까 싶어요.

이건 다소 사족이지만 다음번에 비슷한 코드를 제가 혼자 작성하게 된다면 그냥 jotai를 사용하는 결정을 내리게 될 것 같기는 합니다. 결국은 까고 들어가면 outside-react부분을 라이브러리에 위임하여  가려버린 상황에 불과하겠습니다만..
