### ISSUE TITLE
svg 사용 통일

### ISSUE THREAD

**Issue by Ring-wdr** [u-ga-u-ga/front-end#27]
vite 사용 시 쓰이는 plugin svgr를 적극 활용하는 방향으로 고정합니다.

사용법 ( 건의사항이 있을 경우 댓글 부탁드립니다)
1. shared/ui/icon 폴더에 [제목].svg 형식으로 등록
<img width="101" alt="image" src="https://github.com/u-ga-u-ga/front-end/assets/70439662/f586e038-53b3-41a9-a07e-7fe9024ebde7"><br/>
2. 아래와 같은 형태로 import
<img width="444" alt="image" src="https://github.com/u-ga-u-ga/front-end/assets/70439662/7468595a-6cc9-4a24-801f-e64e3ba797a4">

(+) svg 파일의 색상을 다양하게 바꿀 필요가 있다면 svg 내부 속성을 currentColor 바꿔줍시다. svg 컴포넌트로 color를 주입하면 원하는 색을 얻을 수 있습니다.
<img width="499" alt="image" src="https://github.com/u-ga-u-ga/front-end/assets/70439662/17dd58b1-0570-4836-8101-325dd15a1dce">

**Comment by aliveornot** [comment]
제 부분 처리했습니다.
