### ISSUE TITLE
design: 공유하기 팝업 창

### ISSUE THREAD

**Issue by Ring-wdr** [u-ga-u-ga/front-end#39]
공유하기 팝업 창 디자인 관리 이슈입니다

**Comment by Ring-wdr** [comment]
큰 디자인 수정없이 shadcn 쓰는건 어떨까요 ㅎㅎ
[알림 창 컴포넌트](https://ui.shadcn.com/docs/components/dialog)<br/>
[drawer 컴포넌트](https://ui.shadcn.com/docs/components/drawer)

**Comment by aliveornot** [comment]
이런 게 있었군요. 겁나 잘 만들어 놨네요 ㅋㅋ 역시 snadcn...
